---
- name: start rundeck
  service: name=rundeckd state=started

- name: restart rundeck
  service: name=rundeckd state=restarted

- name: restart nginx
  service: name=nginx state=restarted

- name: register_elb
  ec2_elb:
    instance_id={{ ansible_ec2_instance_id }}
    region={{ ansible_ec2_placement_region }}
    ec2_elbs={{ item }}
    wait_timeout=120
    state=present
  with_items:
    - "{{ ec2_tags.elb_name }}"
